server:
  port: 8085
  servlet:
    context-path: /robot
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/robot?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: qqqq5210.
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    password: qqqq5210



